config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ('/')
  root 'games#index'

  resources :igdb, only: %i[index]
  resources :games do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  has_many :releases, dependent: :destroy, autosave: true
  has_many :platforms, through: :releases, autosave: true

  has_one :game_status, dependent: :destroy, autosave: true

  has_and_belongs_to_many :genres, autosave: true

  accepts_nested_attributes_for :game_status,
                                reject_if: ->(attributes) { attributes['status'].blank? },
                                allow_destroy: true

  validates :name, presence: { unless: :igdb_id }
  validates :igdb_id, numericality: { only_integer: true, greater_than: 0 }, uniqueness: true, allow_nil: true

  after_create :import_igdb_data

  private

  def import_igdb_data
    IGDB::ImportGameJob.perform_later(igdb_id)
  end
end

app/models/game_status.rb
# frozen_string_literal: true

class GameStatus < ApplicationRecord
  enum status: { wishlist: 0, backlog: 1, ready_to_play: 2, playing: 3,
                 beaten: 4, completed: 5, shelved: 6, abandoned: 7 }

  belongs_to :game
end

app/models/genre.rb
# frozen_string_literal: true

class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :slug, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true

  after_create :import_igdb_data

  private

  def import_igdb_data
    IGDB::ImportGenreJob.perform_later(igdb_id)
  end
end

app/models/platform.rb
# frozen_string_literal: true

class Platform < ApplicationRecord
  belongs_to :platform_family, optional: true

  validates :name, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :slug, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true

  after_create :import_igdb_data

  private

  def import_igdb_data
    IGDB::ImportPlatformJob.perform_later(igdb_id)
  end
end

app/models/platform_family.rb
# frozen_string_literal: true

class PlatformFamily < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :slug, uniqueness: { case_sensitive: false }, allow_nil: true
  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true
end

app/models/release.rb
# frozen_string_literal: true

class Release < ApplicationRecord
  enum region: { europe: 1, north_america: 2, australia: 3, new_zealand: 4,
                 japan: 5, china: 6, asia: 7, worldwide: 8, korea: 9, brazil: 10 }, _prefix: true

  belongs_to :game
  belongs_to :platform

  validates :igdb_id, presence: true, numericality: { only_integer: true }, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]
  before_action :set_session_filters, only: %i[index]

  # GET /games or /games.json
  def index
    @games = Game.includes(:platforms)
                 .then { search_by_name _1 }
                 .then { filter_by_platform _1 }
                 .then { apply_order _1 }
  end

  # GET /games/1 or /games/1.json
  def show
    IGDB::ImportGameJob.perform_now(params[:id]) if @game.nil?

    set_game
  end

  # GET /games/search or /games/search.json
  def search
    @games = search_igdb(params[:search])
  end

  # GET /games/new
  def new
    @search_params = params.key?(:search) ? search_params : {}
    @igdb_results = search_igdb(@search_params[:name]) if @search_params[:name].present?
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: t('.success') }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    result = @game.update(game_params)
    destroy_status_if_blank

    respond_to do |format|
      if result
        format.html { redirect_to game_url(@game), notice: t('.success') }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy!

    respond_to do |format|
      format.html { redirect_to games_url, notice: t('.success') }
      format.json { head :no_content }
    end
  end

  private

  def search_by_name(scope)
    session['filters']['name'].present? ? scope.where('name like ?', "%#{session['filters']['name']}%") : scope
  end

  def filter_by_platform(scope)
    if session['filters']['platform'].present?
      scope.where(platforms: { id: session['filters']['platform'] })
    else
      scope
    end
  end

  def apply_order(scope)
    scope.order(session['filters'].slice('order', 'direction').values.join(' '))
  end

  def search_igdb(game_name)
    game_name.present? ? IGDB::Client::Games.search(game_name) : []
  rescue IGDB::Client::Errors::NotFound
    []
  end

  def destroy_status_if_blank
    @game.game_status.destroy if @game.game_status.present? && @game.game_status.status.blank?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find_by(igdb_id: params[:id])
  end

  def set_session_filters
    session['filters'] ||= {}
    session['filters'].merge!(filter_params)

    Rails.logger.debug { "Filters: #{session['filters']}" }
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :igdb_id, game_status_attributes: [:status])
  end

  def filter_params
    params.permit(:name, :platform, :order, :direction)
  end

  def search_params
    params.require(:search).permit(:name, :platform)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  def sort_link(column:, label:)
    direction = column == session.dig('filters', 'order') ? next_direction : 'asc'
    link_to(label, games_path(order: column, direction:), data: { turbo_action: 'replace' }, class: 'table-dark')
  end

  def show_sort_indicator(column)
    sort_indicator if session.dig('filters', 'order') == column
  end

  def cover_url(image_id)
    return "https://images.igdb.com/igdb/image/upload/t_cover_big/#{image_id}.webp" if image_id.present?
  end

  private

  def next_direction
    session.dig('filters', 'direction') == 'asc' ? 'desc' : 'asc'
  end

  def sort_indicator
    tag.span(class: "fas fa-solid fa-sort-#{session.dig('filters', 'direction') == 'asc' ? 'up' : 'down'}")
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game)  do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name, class: "form-control form-control-dark text-bg-dark" %>
      <br>
    </div>

    <div>
      <%= form.label :igdb_id, "IGDB ID", style: "display: block" %>
      <%= form.text_field :igdb_id, class: "form-control form-control-dark text-bg-dark" %>
      <br>
    </div>

    <div>
      <%= form.fields_for :game_status do |status_form| %>
        <%= status_form.label :status, style: "display: block" %>
        <%= status_form.select :status,
                                options_for_select([nil] + GameStatus.statuses.keys.map { |status| [status.humanize, status] },
                                                  game.game_status.status),
                                { },
                                class: "form-control form-control-dark text-bg-dark form-select" %>
        <br>
      <% end %>
    </div>

    <div>
      <%= form.submit class: "form-control form-control-dark text-bg-dark" %>
    </div>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <tr>
    <td><%= link_to(game.name, game_path(game.igdb_id), class: 'nav-link') %></td>
    <td><%= game.platforms.uniq.map { |platform|  platform.abbreviation || platform.name }.join(', ') %></td>
  </tr>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<head>
  <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
</head>

<div class="container row mt-2">
  <div class="col">
    <h1>Games</h1>
  </div>

  <div class="col col-lg-2 col-md-7 justify-content-center">
    <%= link_to "New game", new_game_path, class: "btn btn-primary mt-2" %>
  </div>
</div>

<div>
  <%= form_with url: games_path, method: :get, data: { turbo_action: "replace", controller: "auto-submit", turbo_permanent: "" } do |form| %>
    <div class="container row">
      <%= form.text_field :name,
                          placeholder: "Search by name",
                          value: session.dig('filters', 'name'),
                          data: { action: "auto-submit#submit" },
                          class: "col form-control form-control-dark text-bg-dark me-3 col" %>
      <%= form.select :platform,
                      options_for_select(Platform.all.pluck(:name, :id), session.dig('filters', 'platform')),
                      { include_blank: 'All Platforms' },
                      data: { action: "auto-submit#submit" },
                      class: "col form-control form-control-dark text-bg-dark form-select col" %>
    </div>
  <% end %>
</div>

<div id="games", class="mt-3">
  <table id="games_table" class="table table-dark">
    <thead>
      <th scope="col" id="games_name">
        <%= sort_link(column: "games.name", label: "Name") %>
        <%= show_sort_indicator("name") %>
      </th>
      <th scope="col" id="games_platforms">
        <%= sort_link(column: "platforms.name", label: "Platforms") %>
        <%= show_sort_indicator("platforms.name") %>
      </th>
    </thead>

    <tbody>
      <% @games&.each do |game| %>
        <%= render game %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<div id='igdb_search' class='container row'>
  <div id='filters' class='col col-lg-2'>
    <%= form_with(scope: :search,
                  url: new_game_path,
                  method: :get,
                  data: { turbo_action: 'replace',
                          controller: 'auto-submit',
                          turbo_frame: 'igdb_results' }) do |form| %>
      <div id='search_fields'>
        <%= form.label :name, for: 'search_name' %>
        <%= form.text_field :name,
                            value: @search_params[:name] || nil,
                            data: { action: 'auto-submit#submit' },
                            class: 'col form-control form-control-dark text-bg-dark mb-2' %>

        <%= form.label :platform, for: 'search_platform' %>
        <%= form.select :platform,
                        options_for_select(Platform.all.pluck(:name, :id), @search_params[:platform]),
                        { include_blank: 'All Platforms' },
                        data: { action: 'auto-submit#submit' },
                        class: 'col form-control form-control-dark text-bg-dark form-select' %>
      </div>
    <% end %>
  </div>

  <%= turbo_frame_tag 'igdb_results', class: 'col' do %>
    <div class='row row-cols-1 row-cols-md-2 ms-2'>
      <% @igdb_results&.each do |game| %>
        <div data-controller='nav'
             data-nav-url-value='<%= game_path(game['id']) %>'
             data-action="click->nav#goToUrl"
             class='col card text-bg-dark border-secondary p-0 m-1'
             style='width: 200px;'>
          <img src='<%= cover_url(game.dig('cover', 'image_id')) %>' class='card-img-top' alt='<%= game['name'] %> art'>
          <div class='card-body m-0'>
            <p class='card-text'><%= game['platforms']&.map{ |platform| platform['name'] }&.join(', ') %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/games/search.html.erb
<% content_for(:title) { "IGDB Search" } %>

<div class="games new">
  <h2>Import Game</h2>
  <%= form_tag(search_games_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
  <% end %>

  <table class="paddingBetweenCols" summary="Game list">
    <tr class="header">
      <th></th>
      <th>Name</th>
      <th>Platforms</th>
      <th>Genres</th>
    </tr>
    <% @games&.each do |game| %>
      <%= tag.tr(name: game['name']) do %>
        <td><%= button_to "Import", { action: "create" }, params: { game: { igdb_id: game['id'] } }, id: game['name'] %></td>
        <td><%= game['name'] %></td>
        <td><%= game['platforms']&.map{ |platform| platform['name'] }&.join(", ")&.html_safe %></td>
        <td><%= game['genres']&.map{ |genre| genre['name'] }&.join(", ")&.html_safe %></td>
      <% end %>
    <% end %>
  </table>
</div>

app/views/games/show.html.erb
<%= render @game %>

<div>
  <%= link_to "Edit this game", edit_game_path(@game) %> |
  <%= link_to "Back to games", games_path %>

  <%= button_to "Destroy this game", @game, method: :delete %>
</div>

app/views/igdb/index.html.erb
<% content_for(:title) { "New Game" } %>

<div class= "games new">
  <%= form_tag(igdb_index_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
  <% end %>

  <table class="paddingBetweenCols" summary="Game list">
    <tr class="header">
      <th>Name</th>
      <th>Platforms</th>
      <th>Genres</th>
    </tr>
    <% @games&.each do |game| %>
      <%= tag.tr(name: game['name']) do %>
        <td><%= game['name'] %></td>
        <td><%= game['platforms']&.map{ |platform| platform['name'] }&.join(", ")&.html_safe %></td>
        <td><%= game['genres']&.map{ |genre| genre['name'] }&.join(", ")&.html_safe %></td>
      <% end %>
    <% end %>
  </table>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary p-3">
    <div class='container'>
      <a class="navbar-brand pt-1" href="/">
        <%= image_tag("logo_no_text.png", height: "50", width: "auto", class: "d-inline-block align-top", alt: "logo") %>
      </a>

      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to 'Games', games_path, class: "nav-link #{'active' if controller.controller_name == 'games'}" %>
        </li>

        <!-- I have a history of popper not working properly after I think everything is setup.
             Testing dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Test Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item disabled" href="#">Item 1</a></li>
            <li><a class="dropdown-item disabled" href="#">Item 2</a></li>
            <li><a class="dropdown-item disabled" href="#">Item 2</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item disabled" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BacklogManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if content_for? :head %>
      <%= yield :head %>
    <% end %>
  </head>

  <body class="bg-dark text-white">
    <%= render "layouts/navbar" %>

    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert alert-info">
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>